// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Importadora.Infraestructura.AccesoDatos;

public partial class ACTIVIDAD
{
    public int id_actividad { get; set; }

    public string nombre { get; set; }

    public string detalles { get; set; }

    public virtual ICollection<NOTIFICACION> NOTIFICACION { get; set; } = new List<NOTIFICACION>();
}