// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Importadora.Infraestructura.AccesoDatos;

public partial class CONTACTO
{
    public int id_contacto { get; set; }

    public int? id_empresa { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }

    public string telefono { get; set; }

    public string cedula { get; set; }

    public string cargo { get; set; }

    public string correo { get; set; }

    public virtual ICollection<NOTIFICACION> NOTIFICACION { get; set; } = new List<NOTIFICACION>();

    public virtual EMPRESA id_empresaNavigation { get; set; }
}