// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Importadora.Infraestructura.AccesoDatos;

public partial class DETALLEVENTA
{
    public int id_detalle { get; set; }

    public int? id_venta { get; set; }

    public int? id_precio { get; set; }

    public int? cantidad { get; set; }

    public decimal? subtotalProducto { get; set; }

    public decimal? ivaTotal { get; set; }

    public decimal? totalProducto { get; set; }

    public virtual PRECIOPRODUCTO id_precioNavigation { get; set; }

    public virtual VENTA id_ventaNavigation { get; set; }
}