// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Importadora.Infraestructura.AccesoDatos;

public partial class EMPRESA
{
    public int id_empresa { get; set; }

    public string cedula_ruc { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public string pagina_web { get; set; }

    public virtual ICollection<CONTACTO> CONTACTO { get; set; } = new List<CONTACTO>();

    public virtual ICollection<VENTA> VENTA { get; set; } = new List<VENTA>();
}