// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Importadora.Infraestructura.AccesoDatos;

public partial class PRECIOPRODUCTO
{
    public int id_precio { get; set; }

    public int? id_producto { get; set; }

    public int? id_unidadMedida { get; set; }

    public decimal? precio { get; set; }

    public DateOnly? fechaInicio { get; set; }

    public DateOnly? fechaFin { get; set; }

    public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; } = new List<DETALLEVENTA>();

    public virtual PRODUCTO id_productoNavigation { get; set; }

    public virtual UNIDADMEDIDA id_unidadMedidaNavigation { get; set; }
}