// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Importadora.Infraestructura.AccesoDatos;

public partial class ROL
{
    public int id_rol { get; set; }

    public string nombreRol { get; set; }

    public virtual ICollection<USUARIO> id_usuario { get; set; } = new List<USUARIO>();
}