// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Importadora.Infraestructura.AccesoDatos;

public partial class TIPOVENTA
{
    public int id_tipoventa { get; set; }

    public string nombreTipo { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<VENTA> VENTA { get; set; } = new List<VENTA>();
}