// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Importadora.Infraestructura.AccesoDatos;

public partial class UNIDADMEDIDA
{
    public int id_unidadMedida { get; set; }

    public string nombre { get; set; }

    public string simbolo { get; set; }

    public string tipo { get; set; }

    public virtual ICollection<PRECIOPRODUCTO> PRECIOPRODUCTO { get; set; } = new List<PRECIOPRODUCTO>();
}