// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Importadora.Infraestructura.AccesoDatos;

public partial class USUARIO
{
    public int id_usuario { get; set; }

    public string nombre { get; set; }

    public string correo { get; set; }

    public string password { get; set; }

    public bool? estado { get; set; }

    public virtual ICollection<VENTA> VENTA { get; set; } = new List<VENTA>();

    public virtual ICollection<ROL> id_rol { get; set; } = new List<ROL>();
}