// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Importadora.Infraestructura.AccesoDatos;

public partial class VENTA
{
    public int id_venta { get; set; }

    public int? id_empresa { get; set; }

    public int? id_tipoventa { get; set; }

    public int? id_usuario { get; set; }

    public DateOnly? fecha { get; set; }

    public decimal? subtotalTotal { get; set; }

    public decimal? tasaIva { get; set; }

    public decimal? ivaTotal { get; set; }

    public decimal? totalVenta { get; set; }

    public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; } = new List<DETALLEVENTA>();

    public virtual EMPRESA id_empresaNavigation { get; set; }

    public virtual TIPOVENTA id_tipoventaNavigation { get; set; }

    public virtual USUARIO id_usuarioNavigation { get; set; }
}